from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Course)
admin.site.register(CourseMetadata)
admin.site.register(Roster)
admin.site.register(Assignment)
admin.site.register(AssignmentGradingProfile)
admin.site.register(AssignmentPeergradingProfile)
admin.site.register(Question)
admin.site.register(SubQuestion)
admin.site.register(AssignmentSubmission)
admin.site.register(QuestionSubmission)
admin.site.register(GlobalSubrubric)
admin.site.register(GlobalRubric)
admin.site.register(ProbeSubmission)
admin.site.register(ProbeSubmissionQuestion)
admin.site.register(ProbeSubmissionQuestionComment)
admin.site.register(ProbeSubmissionSubquestion)
admin.site.register(ProbeSubmissionSubquestionComment)
admin.site.register(PeerGraders)
admin.site.register(PeerSubmissionQuestion)
admin.site.register(PeerSubmissionSubquestion)
admin.site.register(Marks)
